### ISSUE TITLE
Protobuf error when running pipeline voice agent example

### ISSUE THREAD

**Issue by Njuelle** [livekit/agents-js#221]
Hello Livekit team,

After building the project and the examples (on the lastest version of `agent-js`), when I run the `pipeline_voice_agent` example, I encounter this Protobuf error when a user joins a room, which gets thrown and stops the agent's process.

```
Error: Load model from /Users/nicolasjuelle/Projects/agents-js/plugins/silero/dist/silero_vad.onnx failed:Protobuf parsing failed.
    at new OnnxruntimeSessionHandler (/Users/nicolasjuelle/Projects/agents-js/node_modules/.pnpm/onnxruntime-node@1.19.2/node_modules/onnxruntime-node/dist/backend.js:24:92)
    at Immediate.<anonymous> (/Users/nicolasjuelle/Projects/agents-js/node_modules/.pnpm/onnxruntime-node@1.19.2/node_modules/onnxruntime-node/dist/backend.js:64:29)
    at process.processImmediate (node:internal/timers:478:21)
```

* pnpm version : 9.15.0
* node version : 20.12.2

Do not hesitate if you need more information.
Thanks in advance

**Comment by nbsp** [comment]
did you pull Git LFS? `git lfs pull` should download the Silero VAD model.

**Comment by Njuelle** [comment]
yes, I ran `git lfs pull`, the model has been downloaded. But the error is still here.

**Comment by Njuelle** [comment]
I finally managed to make it work by manually downloading the model and placing it in the `dist/` directory.
Also, I tried to open the model downloaded by Git LSF in https://netron.app/ ang got an "header error".
