### ISSUE TITLE
`Cannot read properties of undefined (reading 'length')` in openai.LLM

### ISSUE THREAD

**Issue by jambudipa** [livekit/agents-js#233]
The following server code from [the repo sample ](https://github.com/livekit/agents-js/blob/main/examples/src/pipeline_voice_agent.ts)produces the subsequent errors:
```typescript
import type { JobProcess } from '@livekit/agents';
import {
  AutoSubscribe,
  type JobContext,
  WorkerOptions,
  cli,
  defineAgent,
  llm,
  pipeline,
} from '@livekit/agents';
import * as deepgram from '@livekit/agents-plugin-deepgram';
import * as openai from '@livekit/agents-plugin-openai';
import * as silero from '@livekit/agents-plugin-silero';
import dotenv from 'dotenv';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.join(__dirname, '../.env.local');

dotenv.config({ path: envPath });

export default defineAgent({
  prewarm: async (proc: JobProcess) => {
    proc.userData.vad = await silero.VAD.load();
  },
  entry: async (ctx: JobContext) => {
    const vad = ctx.proc.userData.vad! as silero.VAD;
    const initialContext = new llm.ChatContext().append({
      role: llm.ChatRole.SYSTEM,
      text:
        'You are a voice assistant created by LiveKit. Your interface with users will be voice. ' +
        'You should use short and concise responses, and avoiding usage of unpronounceable ' +
        'punctuation.',
    });

    await ctx.connect(undefined, AutoSubscribe.AUDIO_ONLY);
    console.log('waiting for participant');
    const participant = await ctx.waitForParticipant();
    console.log(`starting assistant example agent for ${participant.identity}`);

    const fncCtx: llm.FunctionContext = {
      weather: {
        description: 'Get the weather in a location',
        parameters: z.object({
          location: z.string().describe('The location to get the weather for'),
        }),
        execute: async ({ location }) => {
          console.debug(`executing weather function for ${location}`);
          const response = await fetch(`https://wttr.in/${location}?format=%C+%t`);
          if (!response.ok) {
            throw new Error(`Weather API returned status: ${response.status}`);
          }
          const weather = await response.text();
          return `The weather in ${location} right now is ${weather}.`;
        },
      },
    };

    const agent = new pipeline.VoicePipelineAgent(
      vad,
      new deepgram.STT(),
      new openai.LLM(),
      new openai.TTS(),
      { chatCtx: initialContext, fncCtx },
    );
    agent.start(ctx.room, participant);

    await agent.say('Hey, how can I help you today', true);
  },
});

cli.runApp(new WorkerOptions({ agent: fileURLToPath(import.meta.url) }));
```

> waiting for participant
starting assistant example agent for voice_assistant_user_1461
file:///Users/****/Desktop/livekit/livekit-node-test/node_modules/@livekit/agents/dist/tts/tts.js:167
      charactersCount: this.#text.length,
                                  ^

> TypeError: Cannot read properties of undefined (reading 'length')
    at ChunkedStream.monitorMetrics (file:///Users/****/Desktop/livekit/livekit-node-test/node_modules/@livekit/agents/dist/tts/tts.js:167:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

> Node.js v20.17.0
[10:39:54.476] WARN (63126): job process exited unexpectedly
    err: {
      "type": "Error",
      "message": "Channel closed",
      "stack":
          Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
              at target.send (node:internal/child_process:754:16)
              at Timeout._onTimeout (file:///Users/****/Desktop/livekit/livekit-node-test/node_modules/@livekit/agents/dist/ipc/proc_job_executor.js:47:18)
              at listOnTimeout (node:internal/timers:581:17)
              at process.processTimers (node:internal/timers:519:7)
      "code": "ERR_IPC_CHANNEL_CLOSED"
    }

**Comment by jambudipa** [comment]
Not sure how to apply debugging / logging...why would the text be undefined?

**Comment by heymartinadams** [comment]
Got the same error, but this one caused by (or attributed to) `@livekit/agents-plugin-openai`.

```
file:///Users/.../node_modules/@livekit/agents-plugin-openai/dist/llm.js:413
    return c.length !== void 0;
             ^

TypeError: Cannot read properties of undefined (reading 'length')
    at file:///Users/.../node_modules/@livekit/agents-plugin-openai/dist/llm.js:413:14
    at buildMessage (file:///Users/.../node_modules/@livekit/agents-plugin-openai/dist/llm.js:414:5)
    at file:///Users/.../node_modules/@livekit/agents-plugin-openai/dist/llm.js:287:56
    at Array.map (<anonymous>)
    at #run (file:///Users/.../node_modules/@livekit/agents-plugin-openai/dist/llm.js:287:33)
    at new LLMStream (file:///Users/.../node_modules/@livekit/agents-plugin-openai/dist/llm.js:269:14)
    at LLM.chat (file:///Users/.../node_modules/@livekit/agents-plugin-openai/dist/llm.js:246:12)
    at Object.defaultBeforeLLMCallback [as beforeLLMCallback] (file:///Users/.../node_modules/@livekit/agents/dist/pipeline/pipeline_agent.js:74:20)
    at file:///Users/.../node_modules/@livekit/agents/dist/pipeline/pipeline_agent.js:396:42
    at file:///Users/.../node_modules/@livekit/agents/dist/utils.js:113:7

Node.js v20.18.1
[07:07:31.001] WARN (2828): job process exited unexpectedly
    err: {
      "type": "Error",
      "message": "Channel closed",
      "stack":
          Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
              at target.send (node:internal/child_process:753:16)
              at Timeout._onTimeout (file:///Users/.../node_modules/@livekit/agents/dist/ipc/proc_job_executor.js:47:18)
              at listOnTimeout (node:internal/timers:581:17)
              at process.processTimers (node:internal/timers:519:7)
      "code": "ERR_IPC_CHANNEL_CLOSED"
    }
```

**Comment by heymartinadams** [comment]
I’m guessing that https://github.com/livekit/agents-js/issues/211 might be the same as this error. It seems to occur on subsequent tool calls for me. Definitely a production blocker.

**Comment by heymartinadams** [comment]
I tried to debug, but failing... from what I can tell, `msg.content` is `null` and that case isn’t handled here (although I’m not sure why it’s `null` to begin with, and what can be done to prevent it from being `null` — maybe assign an empty string instead?): https://github.com/livekit/agents-js/blob/main/plugins/openai/src/llm.ts#L608-L631

**Comment by heymartinadams** [comment]
Did that, but it led to another error, indicating that the error source might lie with OpenAI (and not handled in LiveKit).

```
file:///Users/.../node_modules/@livekit/agents-plugin-openai/node_modules/openai/error.mjs:41
            return new BadRequestError(status, error, message, headers);
                   ^

BadRequestError: 400 Invalid value for 'content': expected a string, got null.
    at APIError.generate (file:///Users/.../node_modules/@livekit/agents-plugin-openai/node_modules/openai/error.mjs:41:20)
    at OpenAI.makeStatusError (file:///Users/.../node_modules/@livekit/agents-plugin-openai/node_modules/openai/core.mjs:286:25)
    at OpenAI.makeRequest (file:///Users/.../node_modules/@livekit/agents-plugin-openai/node_modules/openai/core.mjs:330:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #run (file:///Users/.../node_modules/@livekit/agents-plugin-openai/dist/llm.js:282:22) {
  status: 400,
  headers: {
    'access-control-expose-headers': 'X-Request-ID',
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '9062fa1c6f3754a9-YYZ',
    connection: 'keep-alive',
    'content-length': '188',
    'content-type': 'application/json',
    date: 'Wed, 22 Jan 2025 22:28:26 GMT',
    'openai-organization': 'onetask-inc',
    'openai-processing-ms': '301',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'set-cookie': '...',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'x-content-type-options': 'nosniff',
    'x-ratelimit-limit-requests': '5000',
    'x-ratelimit-limit-tokens': '4000000',
    'x-ratelimit-remaining-requests': '4999',
    'x-ratelimit-remaining-tokens': '3998016',
    'x-ratelimit-reset-requests': '12ms',
    'x-ratelimit-reset-tokens': '29ms',
    'x-request-id': 'req_65ed58b78ca6b105d6600ac44f33c1cd'
  },
  request_id: 'req_65ed58b78ca6b105d6600ac44f33c1cd',
  error: {
    message: "Invalid value for 'content': expected a string, got null.",
    type: 'invalid_request_error',
    param: 'messages.[18].content',
    code: null
  },
  code: null,
  param: 'messages.[18].content',
  type: 'invalid_request_error'
}
```

**Comment by nbsp** [comment]
`null` is indeed weird — would make more sense if it was `undefined`. do you have a minimal reproducible example? retrying an LLM function call works fine on my end

**Comment by heymartinadams** [comment]
Haven’t been able to replicate it of late, FYI — (also just started working on it today). Will keep post here if it happens again...

**Comment by mph6083** [comment]
I have seen it a few times in the past 2 days, most often during interruptions. It seems to happen at random. 

I've noticed that it usually happens right after the pipeline.VPAEvent.AGENT_SPEECH_COMMITTED event fires an event with empty content:
`ChatMessage {
  role: 2,
  id: undefined,
  name: undefined,
  content: '',
  toolCalls: undefined,
  toolCallId: undefined,
  toolException: undefined
}`

accompanying error logs:

```
file:///C:/Users/matth/workspace/dsp-base/node_modules/openai/error.mjs:41
            return new BadRequestError(status, error, message, headers);
                   ^

BadRequestError: 400 Invalid value for 'content': expected a string, got null.
    at APIError.generate (file:///C:/Users//workspace/node_modules/openai/error.mjs:41:20)
    at OpenAI.makeStatusError (file:///C:/Users//workspace/node_modules/openai/core.mjs:286:25)
    at OpenAI.makeRequest (file:///C:/Users//workspace/node_modules/openai/core.mjs:330:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #run (file:///C:/Users//workspace/node_modules/@livekit/agents-plugin-openai/dist/llm.js:282:22) {
  status: 400,
  headers: {
    'access-control-expose-headers': 'X-Request-ID',
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '...',
    connection: 'keep-alive',
    'content-length': '187',
    'content-type': 'application/json',
    date: 'Wed, 29 Jan 2025 16:20:22 GMT',
    'openai-organization': 'cents-xugtrp',
    'openai-processing-ms': '82',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'set-cookie': '...',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'x-content-type-options': 'nosniff',
    'x-ratelimit-limit-requests': '5000',
    'x-ratelimit-limit-tokens': '450000',
    'x-ratelimit-remaining-requests': '4999',
    'x-ratelimit-remaining-tokens': '449558',
    'x-ratelimit-reset-requests': '12ms',
    'x-ratelimit-reset-tokens': '58ms',
    'x-request-id': '...'
  },
  request_id: '...',
  error: {
    message: "Invalid value for 'content': expected a string, got null.",
    type: 'invalid_request_error',
    param: 'messages.[9].content',
    code: null
  },
  code: null,
  param: 'messages.[9].content',
  type: 'invalid_request_error'
}```

**Comment by nbsp** [comment]
leaving this issue open since the original comment is about a different issue, but @heymartinadams' issue should be fixed in #296
